default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS", 5) }.to_i %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  url: <%= ENV["DATABASE_URL"] %>
  <% if ENV["DB_SOCKET"].to_s.strip != "" %>
  socket: <%= ENV["DB_SOCKET"] %>
  <% end %>

development:
  <<: *default
  database: big5_quest_development

test:
  <<: *default
  database: big5_quest_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "big5_quest_production") %>
  username: <%= ENV.fetch("DB_USERNAME", "big5_quest") %>
  password: <%= ENV["DB_PASSWORD"] || ENV["BIG5_QUEST_DATABASE_PASSWORD"] %>