name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: ""   # brakeman を入れるために無効化
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: ""   # rubocop を入れるために無効化
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_DATABASE: big5_quest_test
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10
    env:
      BUNDLE_WITHOUT: ""      # dev/test を除外しない
      RAILS_ENV: test
      DB_HOST: 127.0.0.1      # database.yml の host 解決を安定させる
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
      - run: bin/rails db:prepare
      - run: bundle exec rspec --format progress