name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: ""
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bundle exec brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: ""
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports: ["3306:3306"]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: big5_quest_test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=60

    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: big5_quest_test
      BUNDLE_WITHOUT: ""

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Wait for MySQL
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          for i in {1..60}; do
            mysql -h127.0.0.1 -P3306 -uroot -proot -e 'SELECT 1' && break
            sleep 2
          done

      - name: DB prepare
        run: bin/rails db:prepare

      - name: Run RSpec
        run: bundle exec rspec --format progress