name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches: [ main, chore/cd-frontend ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_frontend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      # dist に /api なしのURLが紛れ込んでないか、/api ベースが埋め込まれているかを検査
      - name: Verify API base url baked in bundle
        run: |
          # /api なしの誤URLがあれば落とす
          if grep -RIn "https://api.big5-quest.com/diagnosis_forms" dist; then
            echo "ERROR: /api なしのURLが残っています"; exit 1
          fi
          # /api ベースのURL、または api/diagnosis_forms の文字列が入っていればOK
          if grep -RIn "https://api.big5-quest.com/api" dist >/dev/null || \
             grep -RIn "api/diagnosis_forms" dist >/dev/null ; then
            echo "OK: /api ベースURLがバンドルに含まれています"
          else
            echo "ERROR: /api ベースURLが見つかりません"; exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync static assets to S3 (except index.html)
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload index.html with no-cache
        run: |
          aws s3 cp dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/index.html"
