name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches: [ main, chore/cd-frontend ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy_frontend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Verify API base url baked in bundle
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          set -euo pipefail
          BASE="${VITE_API_BASE_URL%/}"   # 末尾 / を除去
          if [ -z "${BASE}" ]; then
            echo "ERROR: VITE_API_BASE_URL is empty"; exit 1
          fi
          if [[ "${BASE}" != *"/api" ]]; then
            echo "ERROR: VITE_API_BASE_URL must end with /api (got: ${BASE})"; exit 1
          fi

          WRONG="${BASE%/api}/diagnosis_forms"
          if grep -RIn "${WRONG}" dist >/dev/null; then
            echo "ERROR: Found wrong URL without /api: ${WRONG}"; exit 1
          fi

          if grep -RIn "${BASE}" dist >/dev/null || \
             grep -RIn "/diagnosis_forms" dist >/dev/null ; then
            echo "OK: API URL check passed"
          else
            echo "ERROR: API base or endpoints not found in bundle"
            exit 1
          fi

          echo "Expecting API base: ${BASE}"
          echo "---- Sample matches in bundle ----"
          grep -RInoE '/diagnosis_forms|/api/diagnosis_forms' dist | head -20 || true
          echo "----------------------------------"

          if grep -RIn "${BASE}/diagnosis_forms" dist >/dev/null || \
             grep -RIn "/api/diagnosis_forms" dist   >/dev/null ; then
            echo "OK: /api ベースURLでビルドされています"
          else
            echo "ERROR: /api ベースURLが見つかりません（${BASE} / または /api/diagnosis_forms）"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync static assets to S3 (except index.html)
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload index.html with no-cache
        run: |
          aws s3 cp dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/index.html"
